# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_call_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='call',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='call',
            name='state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('won', 'Succeeded'), ('lost', 'Failed')], default='accepted', max_length=16),
            preserve_default=False,
        ),
    ]
