# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Lorem ipsum'),
            preserve_default=False,
        ),
    ]
