# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
