# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.IntegerField(default=1, verbose_name='badge level'),
        ),
    ]
