# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160604_1203'),
        ('core', '0009_auto_20160604_1037'),
    ]

    operations = [
    ]
