# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


def add_slugs(apps, schema):
    for category in apps.get_model('core.Category').objects.all():
        category.slug = category.name.lower()
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(add_slugs)
    ]
