# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_slug'),
        ('core', '0011_badge_validator'),
    ]

    operations = [
    ]
