# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bookmark'),
        ('core', '0015_sites'),
    ]

    operations = [
    ]
