# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160605_0714'),
        ('core', '0018_auto_20160605_1131'),
    ]

    operations = [
    ]
