# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:33
from __future__ import unicode_literals

from django.db import migrations


def delete_badges(apps, schema):
    for user_badge in apps.get_model('core.UserBadge').objects.all():
        user_badge.delete()

    for badge in apps.get_model('core.Badge').objects.all():
        badge.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userbadge_level'),
    ]

    operations = [
        migrations.RunPython(delete_badges)
    ]
