# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:45
from __future__ import unicode_literals

from django.db import migrations

def create_badges(apps, schema):
    category_model = apps.get_model('core.Badge')

    category_model.objects.create(name="First Mystery completed", description="Complete 1 Mystery task", slug="mystery",  validator="int(bool(user_calls.filter(task__category__slug='mystery').count()))")
    ##############################
    category_model.objects.create(name="First Geo completed", description="Complete 1 Geo task",  slug="geo", validator="int(bool(user_calls.filter(task__category__slug='geo').count()))")
    ##############################
    category_model.objects.create(name="First Selfie completed", description="Complete 1 Selfie task",  slug="selfie", validator="int(bool(user_calls.filter(task__category__slug='selfie').count()))")
    ##############################
    category_model.objects.create(name="First Team completed", description="Complete 1 Team task",  slug="team", validator="int(bool(user_calls.filter(task__category__slug='team').count()))")
    ##############################
    category_model.objects.create(name="First Stranger completed", description="Complete 1 Stranger task",  slug="stranger", validator="int(bool(user_calls.filter(task__category__slug='stranger').count()))")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_badge_slug'),
    ]

    operations = [
        migrations.RunPython(create_badges)
    ]
