# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160605_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
